mbed TLS v2.7.0: sha512.h File Reference
sha512.h File Reference
The SHA-384 and SHA-512 cryptographic hash function.
#include "config.h"
#include <stddef.h>
#include <stdint.h>
Data Structures
struct mbedtls_sha512_context
The SHA-512 context structure.
Macros
#define MBEDTLS_ERR_SHA512_HW_ACCEL_FAILED -0x0039
#define MBEDTLS_DEPRECATED
#define MBEDTLS_DEPRECATED
Functions
void mbedtls_sha512_init (mbedtls_sha512_context *ctx)
This function initializes a SHA-512 context.
void mbedtls_sha512_free (mbedtls_sha512_context *ctx)
This function clears a SHA-512 context.
void mbedtls_sha512_clone (mbedtls_sha512_context *dst, const mbedtls_sha512_context *src)
This function clones the state of a SHA-512 context.
int mbedtls_sha512_starts_ret (mbedtls_sha512_context *ctx, int is384)
This function starts a SHA-384 or SHA-512 checksum calculation.
int mbedtls_sha512_update_ret (mbedtls_sha512_context *ctx, const unsigned char *input, size_t ilen)
This function feeds an input buffer into an ongoing SHA-512 checksum calculation.
int mbedtls_sha512_finish_ret (mbedtls_sha512_context *ctx, unsigned char output[64])
This function finishes the SHA-512 operation, and writes the result to the output buffer. This function is for internal use only.
int mbedtls_internal_sha512_process (mbedtls_sha512_context *ctx, const unsigned char data[128])
This function processes a single data block within the ongoing SHA-512 computation.
static MBEDTLS_DEPRECATED void mbedtls_sha512_starts (mbedtls_sha512_context *ctx, int is384)
This function starts a SHA-384 or SHA-512 checksum calculation.
static MBEDTLS_DEPRECATED void mbedtls_sha512_update (mbedtls_sha512_context *ctx, const unsigned char *input, size_t ilen)
This function feeds an input buffer into an ongoing SHA-512 checksum calculation.
static MBEDTLS_DEPRECATED void mbedtls_sha512_finish (mbedtls_sha512_context *ctx, unsigned char output[64])
This function finishes the SHA-512 operation, and writes the result to the output buffer.
static MBEDTLS_DEPRECATED void mbedtls_sha512_process (mbedtls_sha512_context *ctx, const unsigned char data[128])
This function processes a single data block within the ongoing SHA-512 computation. This function is for internal use only.
int mbedtls_sha512_ret (const unsigned char *input, size_t ilen, unsigned char output[64], int is384)
This function calculates the SHA-512 or SHA-384 checksum of a buffer.
static MBEDTLS_DEPRECATED void mbedtls_sha512 (const unsigned char *input, size_t ilen, unsigned char output[64], int is384)
This function calculates the SHA-512 or SHA-384 checksum of a buffer.
int mbedtls_sha512_self_test (int verbose)
The SHA-384 or SHA-512 checkup routine.
Detailed Description
The SHA-384 and SHA-512 cryptographic hash function.
Definition in file sha512.h.
Macro Definition Documentation
MBEDTLS_DEPRECATED [1/2]
#define MBEDTLS_DEPRECATED
Definition at line 260 of file sha512.h.
MBEDTLS_DEPRECATED [2/2]
#define MBEDTLS_DEPRECATED
Definition at line 260 of file sha512.h.
MBEDTLS_ERR_SHA512_HW_ACCEL_FAILED
#define MBEDTLS_ERR_SHA512_HW_ACCEL_FAILED -0x0039
SHA-512 hardware accelerator failed
Definition at line 36 of file sha512.h.
Function Documentation
mbedtls_internal_sha512_process()
int mbedtls_internal_sha512_process (mbedtls_sha512_context * ctx, const unsigned char data[128])
This function processes a single data block within the ongoing SHA-512 computation.
Parameters
ctx The SHA-512 context.
data The buffer holding one block of data.
Returns
0 on success.
Referenced by mbedtls_sha512_process().
mbedtls_sha512()
static MBEDTLS_DEPRECATED void mbedtls_sha512 (const unsigned char * input, size_t ilen, unsigned char output[64], int is384) inline static
This function calculates the SHA-512 or SHA-384 checksum of a buffer.
The function allocates the context, performs the calculation, and frees the context.
The SHA-512 result is calculated as output = SHA-512(input buffer).
Deprecated:
Superseded by mbedtls_sha512_ret() in 2.7.0
Parameters
input The buffer holding the data.
ilen The length of the input data.
output The SHA-384 or SHA-512 checksum result.
is384 Determines which function to use.
0: Use SHA-512.
1: Use SHA-384.
Definition at line 281 of file sha512.h.
References mbedtls_sha512_ret().
mbedtls_sha512_clone()
void mbedtls_sha512_clone (mbedtls_sha512_context * dst, const mbedtls_sha512_context * src)
This function clones the state of a SHA-512 context.
Parameters
dst The destination context.
src The context to clone.
mbedtls_sha512_finish()
static MBEDTLS_DEPRECATED void mbedtls_sha512_finish (mbedtls_sha512_context * ctx, unsigned char output[64]) inline static
This function finishes the SHA-512 operation, and writes the result to the output buffer.
Deprecated:
Superseded by mbedtls_sha512_finish_ret() in 2.7.0
Parameters
ctx The SHA-512 context.
output The SHA-384 or SHA-512 checksum result.
Definition at line 193 of file sha512.h.
References mbedtls_sha512_finish_ret().
mbedtls_sha512_finish_ret()
int mbedtls_sha512_finish_ret (mbedtls_sha512_context * ctx, unsigned char output[64])
This function finishes the SHA-512 operation, and writes the result to the output buffer. This function is for internal use only.
Parameters
ctx The SHA-512 context.
output The SHA-384 or SHA-512 checksum result.
Returns
0 on success.
Referenced by mbedtls_sha512_finish().
mbedtls_sha512_free()
void mbedtls_sha512_free (mbedtls_sha512_context * ctx)
This function clears a SHA-512 context.
Parameters
ctx The SHA-512 context to clear.
mbedtls_sha512_init()
void mbedtls_sha512_init (mbedtls_sha512_context * ctx)
This function initializes a SHA-512 context.
Parameters
ctx The SHA-512 context to initialize.
mbedtls_sha512_process()
static MBEDTLS_DEPRECATED void mbedtls_sha512_process (mbedtls_sha512_context * ctx, const unsigned char data[128]) inline static
This function processes a single data block within the ongoing SHA-512 computation. This function is for internal use only.
Deprecated:
Superseded by mbedtls_internal_sha512_process() in 2.7.0
Parameters
ctx The SHA-512 context.
data The buffer holding one block of data.
Definition at line 210 of file sha512.h.
References mbedtls_internal_sha512_process().
mbedtls_sha512_ret()
int mbedtls_sha512_ret (const unsigned char * input, size_t ilen, unsigned char output[64], int is384)
This function calculates the SHA-512 or SHA-384 checksum of a buffer.
The function allocates the context, performs the calculation, and frees the context.
The SHA-512 result is calculated as output = SHA-512(input buffer).
Parameters
input The buffer holding the input data.
ilen The length of the input data.
output The SHA-384 or SHA-512 checksum result.
is384 Determines which function to use.
0: Use SHA-512.
1: Use SHA-384.
Returns
0 on success.
Referenced by mbedtls_sha512().
mbedtls_sha512_self_test()
int mbedtls_sha512_self_test (int verbose)
The SHA-384 or SHA-512 checkup routine.
Returns
0 on success, or 1 on failure.
mbedtls_sha512_starts()
static MBEDTLS_DEPRECATED void mbedtls_sha512_starts (mbedtls_sha512_context * ctx, int is384) inline static
This function starts a SHA-384 or SHA-512 checksum calculation.
Deprecated:
Superseded by mbedtls_sha512_starts_ret() in 2.7.0
Parameters
ctx The SHA-512 context to initialize.
is384 Determines which function to use.
0: Use SHA-512.
1: Use SHA-384.
Definition at line 159 of file sha512.h.
References mbedtls_sha512_starts_ret().
mbedtls_sha512_starts_ret()
int mbedtls_sha512_starts_ret (mbedtls_sha512_context * ctx, int is384)
This function starts a SHA-384 or SHA-512 checksum calculation.
Parameters
ctx The SHA-512 context to initialize.
is384 Determines which function to use.
0: Use SHA-512.
1: Use SHA-384.
Returns
0 on success.
Referenced by mbedtls_sha512_starts().
mbedtls_sha512_update()
static MBEDTLS_DEPRECATED void mbedtls_sha512_update (mbedtls_sha512_context * ctx, const unsigned char * input, size_t ilen) inline static
This function feeds an input buffer into an ongoing SHA-512 checksum calculation.
Deprecated:
Superseded by mbedtls_sha512_update_ret() in 2.7.0
Parameters
ctx The SHA-512 context.
input The buffer holding the data.
ilen The length of the input data.
Definition at line 176 of file sha512.h.
References mbedtls_sha512_update_ret().
mbedtls_sha512_update_ret()
int mbedtls_sha512_update_ret (mbedtls_sha512_context * ctx, const unsigned char * input, size_t ilen)
This function feeds an input buffer into an ongoing SHA-512 checksum calculation.
Parameters
ctx The SHA-512 context.
input The buffer holding the input data.
ilen The length of the input data.
Returns
0 on success.
Referenced by mbedtls_sha512_update().